resources:
  repositories:
  - repository: build
    type: github
    name: eryph-org/build
    endpoint: eryph-org
    ref: refs/heads/pull/improve-package-restore

trigger:
- main
- refs/tags/v*

extends:
  template: pipelines/templates/dotnetclient.yml@build
  parameters:
    withCmdlet: true
